dist: xenial
sudo: false
language: python
cache: pip
python:
  - 3.8
jobs:
  fast_finish: true
  include:
    - python: 3.8
      env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
    - python: 3.8
      env: REQ="Django>=3.1b1,<3.2"
    - python: 3.7
      env: REQ="Django>=3.1b1,<3.2"
    - python: 3.6
      env: REQ="Django>=3.1b1,<3.2"
    - python: 3.7
      env: REQ="Django>=3.0,<3.1"
    - python: 3.6
      env: REQ="Django>=3.0,<3.1"
    - python: 3.7
      env: REQ="Django>=2.2,<3.1"
    - python: 3.6
      env: REQ="Django>=2.2,<3.0"
    - python: 3.8
      env: REQ="black flake8"
      install: skip
      script:
        - pip install black flake8
        - flake8 .
        - black --check curtains tests
install:
  - pip install -U pip wheel
  - pip install $REQ
  - python setup.py install
script: cd tests && ./manage.py test -v2 testapp
